### ISSUE TITLE
Customize the class of formulate-form-errors and formulate-form-error

### ISSUE THREAD

**Issue by danielmoessner** [wearebraid/vue-formulate#252] opened 2020-09-17 12:15 UTC
Hello, 

I'm using Tailwind CSS and I would like to also customize general form errors not bound to any field.

I'm not sure if that is possible yet. The documentation does not show any element key for the general errors.

**Comment by justin-schroeder** [comment] 2020-09-17 13:35
I agree this needs to be included. It's a duplicate of #180, so I'll close this and let you track that issue for updates. Currently slated for `2.5.0`. Best of luck!

**Closed as completed by justin-schroeder** 2020-09-17 13:35 UTC
Labels: duplicate, feature request
