### ISSUE TITLE
Customize component name

### ISSUE THREAD

**Issue by chadwtaylor** [wearebraid/vue-formulate#214] opened 2020-08-01 15:29 UTC
To keep apps clean and maintainable, would it be possible to customize the component name from `<FormulateInput>` to `<AppInput>` for example?

**Comment by justin-schroeder** [comment] 2020-08-02 14:39
Hi @chadwtaylor.

The plugin system gives you access to modify almost everything, including this. There aren't specific tests to ensure non-regression on it, but its pretty trivial with a plugin. Here's a two-liner to change `FormulateInput` to `AppInput`:

```js
function changeInputName (instance) {
  const { FormulateInput, ...components } = instance.options.components
  instance.options.components = { ...components, ...{ AppInput: FormulateInput } }
}

Vue.use(VueFormulate, {
  plugins: [ changeInputName ]
})
```

And here's that plugin used in a sandbox: https://codesandbox.io/s/vue-formulate-change-component-name-60f3h?file=/src/components/Reproduction.vue

Good luck 👍

**Comment by justin-schroeder** [comment] 2020-08-03 19:41
If there are others issues with this feel free to open a new issue, but I'll close it for now since i have a backlog building up 👍

**Closed as completed by justin-schroeder** 2020-08-03 19:41 UTC
Labels: feature request
