### ISSUE TITLE
Access form/field errors within a custom input

### ISSUE THREAD

**Issue by quimarche** [wearebraid/vue-formulate#57] opened 2020-03-26 16:51 UTC
I'm trying to enable/disable submit buttons depending on the validation status of other fields in the form. How might I do this? i.e. which property or chain of properties can I access to determine the validation status?

**Comment by justin-schroeder** [comment] 2020-03-26 17:48
## Coming Soon
@quimarche Good question, the short answer, is that there isn't a great way to do this at this precise moment, but `2.3` should be coming out soon with elegant support for these kinds of features using scoped slots, and named forms. For that reason I'll close this as a duplicate of #34, but its a solid request.

## Current State
That said, it is possible today, just not super "pretty".

```vue
<template>
<FormulateForm
  ref="form"
  @input="checkValidation"
>
 ... inputs here ...
  <FormulateInput
    :disabled="hasErrors"
    type="submit"
  />
</FormulateForm>
</template>

<script>
export default {
  data () {
    hasErrors: false
  },
  methods: {
    async checkValidation () {
      // Even better if you debounce this a bit
      this.hasErrors = await this.$refs.form.hasValidationErrors()
    }
  }
}
</script>
```

Let me know if you have other issues with this.

**Closed as completed by justin-schroeder** 2020-03-26 17:48 UTC
Labels: feature request

**Comment by fidelix** [comment] 2020-07-20 07:43
How would this be done more cleanly in 2.3+ ?
