### ISSUE TITLE
Specialized Currency Type

### ISSUE THREAD

**Issue by christianechevarria** [wearebraid/vue-formulate#243] opened 2020-09-06 00:14 UTC
**Describe the new feature you'd like**

Capturing monetary figured is an incredibly common use-case for forms, but there is no specialized component type for it --

In the docs, we have various types of inputs that are sub-types, Text has the most by far: 
![image](https://user-images.githubusercontent.com/23618650/92315283-226f2c00-ef98-11ea-8005-1dfd3d355fe4.png)

There is a number example, but it doesn't exactly fit the money format of XX.XX - validating this format is not difficult at all, in fact there is a robust StackOverflow answer with a regex to handle various scenarios: https://stackoverflow.com/questions/16242449/regex-currency-validation

it would be nice to have a ready-made example like this:

```
<FormulateInput
  type="currency"
  name="sample"
  label="Sample number input"
  placeholder="Sample number placeholder"
  help="Sample number help text"
  validation="required|number|between:10,20"
  min="0"
  max="99.99"
  error-behavior="live"
/>

```

Which I'm currently achieving like this:

```
<FormulateInput
  v-model="customerEstimate"
  type="text"
  inputmode="numeric"
  pattern="^\$?(([1-9]\d{0,2}(,\d{3})*)|0)?\.\d{1,2}$"
  min="0"
  name="Customer estimate"
  label="How much do you think this is worth?"
/>
```

Another nice feature for users is to auto-format whole numbers to include the two decimal places which can be achieved by rewriting the value conditionally on the blur event (will add this here once I've written it)

Update:

Have added a simple onBlur event handler that re-writes the target value of the input, but it only seems to work after the second on-blur event (I think this can be due to VueFormulate's error-handling), here's the code

```
    onBlur(e) {
      // Coerce input value into number, strange format is much more performant than Number constructor
      // https://stackoverflow.com/questions/15865346/coerce-to-number
      const number = e.target.value * 1
      e.target.value = number.toFixed(2)
    },
```

This approach seems to work: https://jsfiddle.net/mani04/bgzhw68m/ but I don't want to create a higher-order component. Any help @justin-schroeder  ?

Update 2:

Applied the onBlur handler to a plain input and it works as intended

```
<input type="text" @blur="onBlur" />
```

**Comment by justin-schroeder** [comment] 2020-09-09 14:08
Thanks for the nice write up :)

This particular case I think we're either looking at a synthetic element (plugin ecosystem should/could solve this over time, but not something we will be doing in core) or input masking (which will be in core). So for now I'll mark/close this as a duplicate of #67 which is on the roadmap.

In the meantime, you could definitely do what you're after with a custom input by manipulating the `context.model` manually on input or on blur the way you're doing now. Then you wouldn't need that HOC, and heck you could even be the person to create the first currency input plugin 🎉

You can also checkout @gahabeen's [vue-formulate-extended](https://github.com/gahabeen/vue-formulate-extended) plugin which includes support for some features that are still "to come" in core like input masking.

**Closed as completed by justin-schroeder** 2020-09-09 14:08 UTC
Labels: duplicate, feature request
