### ISSUE TITLE
Validate another field when current field is blurred

### ISSUE THREAD

**Issue by pimhooghiemstra** [wearebraid/vue-formulate#72] opened 2020-04-29 07:07 UTC
**Describe the new feature you'd like**
In an address form with zipcode and country we often have strict rules for the zipcode based on the country. I created a custom rule for both the zipcode and the country field using the getFormValues but this is not enough for all situations.
When the zipcode validation fails due to the wrong country selected and the user changes the country for which the zipcode does match, the zipcode validation message remains as the zipcode field is not validated at that point.
Even more so, blurring from the zipcode field (without changing it) also does not revalidate and the validation message remains.

The requested feature would be the option to validate another field when the current field is changed.

**What percentage of vue-formulate users would benefit?**
I am not sure, but when working with addresses I think this would benefit a lot of users.

**Comment by justin-schroeder** [comment] 2020-04-29 13:48
This is definitely an issue @pimhooghiemstra, thanks for filing this report. It's technically a duplicate of #68, but that one has a less helpful title so I might merge the two together. The ultimate fix for this is probably a little bit away since it will depend on the significant `v2.3` update.

However you *should* be able to make this work if you upgrade to `v2.2.9` or later (released yesterday — April 28th) and then use a different field for each possible zip code type. For example:

```vue
<FormulateInput
  name="zip"
  validation="myCustomRule"
  v-if="country === 'US'"
/>
<FormulateInput
  name="zip"
  validation="myCustomRule"
  v-else
/>
<FormulateInput
  v-model="country"
  name="country"
  type="select"
  options="{US: 'United States', EU: "Europe"}
/>
```

Again, this would require the de-register bugfix in 2.2.9...and admitedly its a bit of a hack compared to having a proper dependency tree like is proposed in #68, but it should work for your use case.

Also #68 is still open for suggestions if you have other ideas on how you would like to see that work.

**Closed as completed by justin-schroeder** 2020-04-29 13:48 UTC
Labels: duplicate, feature request

**Comment by pimhooghiemstra** [comment] 2020-04-30 12:23
Thank you @justin-schroeder for your response, I will give it a try. Although it seems like a bit of a hack initially, I think it also cleans up the validation rules by having to write one for each zipcode field instead of a single one which than uses a switch for the country. Anyway, looking forward to v2.3
