### ISSUE TITLE
Label slot or label hover tooltips

### ISSUE THREAD

**Issue by carrera** [wearebraid/vue-formulate#53] opened 2020-03-26 09:35 UTC
**Describe the new feature you'd like**
A label slot so we can add our own label format.
or
Label hover tooltips with slot possibility (so we can add our own icons where we can hover over.)

**What percentage of vue-formulate users would benefit?**
80%

**Comment by carrera** [comment] 2020-03-26 09:35
or both ofc :P

**Comment by justin-schroeder** [comment] 2020-03-26 13:25
I hear you loud and clear on that one.

So, the label is already a scoped slot (name `label`) however this is not technically a public API, and as such will be changing slightly in the `2.3.0` update, so use it at your own risk (upgrade wont be very hard). The 2.3.0 update will address pretty much all scoped slot concerns, so I'll consider that portion of this a duplicate of #34).

As for the tooltip can you maybe send a screenshot of what you're thinking? I've thought about adding one additional prop for an info circle at the end of a label.

**Comment by carrera** [comment] 2020-03-27 10:04
Yeah an info circle seems like enough because if people want something different they could just use the label slot to create one themselves i guess.

**Comment by justin-schroeder** [comment] 2020-03-27 13:56
seems reasonable. I'll add this to the roadmap for a future release, although it probably will be after `v2.3`, but 2.3 will give scoped slot support for those that want to create this interaction on their own.

**Comment by carrera** [comment] 2020-03-27 13:58
Nice, thanks! Really cool that you respond so quickly.

**Comment by justin-schroeder** [comment] 2020-05-22 18:12
Considering this closed. We won't directly implement a tooltip, but its pretty easy to do now. You can even read an article I wrote that uses it as an example of how to extend formulate here:

https://dev.to/justinschroeder/introducing-vue-formulate-truly-delightful-form-authoring-56f5

**Closed as completed by justin-schroeder** 2020-05-22 18:12 UTC
Labels: future
