### ISSUE TITLE
File doesn't remove from submit data

### ISSUE THREAD

**Issue by maksabuzyarov** [wearebraid/vue-formulate#245] opened 2020-09-06 19:39 UTC
**Describe the bug**
File doesn't remove from data in the ```submitHandler(data)``` after click on remove icon.

**To Reproduce**
1. Go to [this codepen](https://codepen.io/maksabuzyarov/pen/vYGppEa) and open debug view (In edit mode, the file field does not work for me)
2. Add the file to the avatar field
2. Click on ```Save profile```. Now the uploaded file can be seen in the data object
3. Click on remove icon. File removed from field, but:
4. Click on ```Save profile```. The file is still present in the data object

**Reproduction**
CodePen: [https://codepen.io/maksabuzyarov/pen/vYGppEa](https://codepen.io/maksabuzyarov/pen/vYGppEa)

**Expected behavior**
I think that the file description should not be present in the data object after deleting it

**Screenshots**
1. File added, clicked on ```Save profile```.
![image](https://user-images.githubusercontent.com/20745248/92333842-42cee180-f091-11ea-8ae0-da293b36607d.png)

2. File removed. clicked  on ```Save profile```.
![image](https://user-images.githubusercontent.com/20745248/92333854-63973700-f091-11ea-8809-cebfcf7b887a.png)

**Device information:**
 - Device: notebook MSI
 - OS: Windows 10
 - Browser: Google Chrome 85.0.4183.83

**Comment by maksabuzyarov** [comment] 2020-09-13 22:12
I checked the branch **2.4.4**. 

It works, thanks!

**Comment by justin-schroeder** [comment] 2020-09-19 14:26
Yep! Fixed in release/2.4.4 (not quite published yet)

**Comment by maksabuzyarov** [comment] 2020-10-07 09:06
@justin-schroeder 
In version 2.4.5 It does not work again :(

**Reproduction (copied)**
CodePen: https://codepen.io/maksabuzyarov/pen/vYGppEa

**Comment by justin-schroeder** [comment] 2020-10-07 13:47
Damn, a regression eh? Thats why having tests on these things would be really nice....ok I'll reopen this. in the meantime lock 2.4.4 in

**Comment by justin-schroeder** [comment] 2020-10-07 15:56
@acemir I think this has to do with the updates in 2.4.5 in your PR. I imagine its an easy fix, any chance you want to tackle it?

**Comment by acemir** [comment] 2020-10-07 16:32
> @acemir I think this has to do with the updates in 2.4.5 in your PR. I imagine its an easy fix, any chance you want to tackle it?

@justin-schroeder Of course. I'll take a look at this scenario in a moment!

**Comment by StephenMarkToms** [comment] 2020-10-28 16:31
> > @acemir I think this has to do with the updates in 2.4.5 in your PR. I imagine its an easy fix, any chance you want to tackle it?
> 
> @justin-schroeder Of course. I'll take a look at this scenario in a moment!

Did some digging into this problem myself. Looks like when the file is removed from the grouping you're not emitting the new value of the form file input. I think it would be as simple as that.

**Comment by justin-schroeder** [comment] 2020-12-29 18:58
Phew, ok good news on this front. This is now fixed in `release/2.5.0` (not released as of writing, but usable) and we've gone through the effort of getting cypress tests in place to prevent regressions here again.

**Closed as completed by justin-schroeder** 2020-12-29 18:58 UTC
Labels: bug, ready for release
