### ISSUE TITLE
Is it possible to include FormulateForm into a current form ?

### ISSUE THREAD

**Issue by k-slash** [wearebraid/vue-formulate#224] opened 2020-08-14 12:04 UTC
Hi,
I would like to verify my FormulateForm not through vue-formulate input type submit but through a method of another button. I mean, I have a form and inside this I include vue formulate and when I submit my form, I would like to verify my FormulateForm before sending data.
Is there a way to do that ?

Thanks,

**Comment by justin-schroeder** [comment] 2020-08-14 19:58
A code example would be really helpful here I think, but one thing I would not recommend is nesting `<FormulateForm>` inside a `<form>`. But there's no reason why your `<FormulateForm>` cannot be the outtermost wrapping element, its just a `<form>` element itself. Of course, you can [submit your form programmatically too](https://codepen.io/justin-schroeder/pen/qBbEZGX).

I'm going to close this since it's not a bug. Feel free to keep looking for help on one of the community "channels" https://vueformulate.com/guide/community/#questions-and-support

**Closed as completed by justin-schroeder** 2020-08-14 19:58 UTC
Labels: bug report

**Comment by k-slash** [comment] 2020-08-15 16:50
Thank you for your quick response, it helped me a lot. And sorry to ask my question here, I had put it on Stackoverflow but I didn't get any answer. My problem was : I have a default form and I want to enrich it with vue formulate. 
And now it works like a charm. Here is [an example](https://codesandbox.io/s/nifty-tdd-tcd4h?file=/src/App.vue)

Thank you so much for this plugin !

**Comment by justin-schroeder** [comment] 2020-08-15 21:26
Thanks! Nice form!
