### ISSUE TITLE
uploadPromise for initial values

### ISSUE THREAD

**Issue by maksabuzyarov** [wearebraid/vue-formulate#303] opened 2020-10-27 12:37 UTC
**Describe the bug**
When initializing the form, I set the initial values ​​for the ```file``` field. After that, without changing the files, I click on submit. The files start to be uploaded to the server via ```upload```, although I have not added new files.

I assume this is because the ```file``` field with a predefined value does not exist the value ```uploadPromise``` (#271 ), which determines whether they are uploaded to the server or not.

**To Reproduce**
1. Go to [https://codepen.io/maksabuzyarov/pen/bGeWdGe](https://codepen.io/maksabuzyarov/pen/bGeWdGe)
2. Click on 'Submit'
3. Look at the files

### CodePen:

[https://codepen.io/maksabuzyarov/pen/bGeWdGe](https://codepen.io/maksabuzyarov/pen/bGeWdGe)

**Expected behavior**
Uploading to the server should not be performed for these files. And it cannot, because I did not transfer the contents of the file.

**Screenshots**
![image](https://user-images.githubusercontent.com/20745248/97301858-51ec3780-1869-11eb-9d94-ac661ae746a4.png)

**Comment by justin-schroeder** [comment] 2020-10-27 13:29
@maksabuzyarov this may be a regression in 2.4.5 — Can you try 2.4.4? We fixed some bugs in 2.4.5 specific to file uploads and it introduced other issues. Its the one area of the framework that doesnt have tests due to a JSDom limitation, so the plan is to introduce Cypress tests in 2.5 specifically for the file inputs.

**Comment by maksabuzyarov** [comment] 2020-10-27 14:01
Yes, version 2.4.4 does not have this bug. Because ```uploadPromise``` appeared in #271 .

But in version 2.4.4 there is another bug (fixed in #274  and applied in 2.4.5): there is no ```__id``` in the ```results``` array if the initial value is passed (added only for upload). Because of this, files from the multiple field are not removed.

Therefore, I described only the error in the current version.

**Comment by acemir** [comment] 2020-10-28 02:11
@maksabuzyarov Fortunately #280 fixes this problem among others. The initial files are considered already uploaded and can be successfully removed. Check it here https://codepen.io/acemir/pen/bGeGaBV.

**Comment by maksabuzyarov** [comment] 2020-10-28 07:43
@acemir 
I checked codepen and was unable to reproduce the bug described here and described in #245 

Thank you!

**Comment by justin-schroeder** [comment] 2020-12-29 19:58
This is now fixed in `release/2.5.0` and includes a cypress backing test 👍

**Closed as completed by justin-schroeder** 2020-12-29 19:58 UTC
Labels: bug
