### ISSUE TITLE
Duplicate Key Warning in Form Group Schema

### ISSUE THREAD

**Issue by lsbyerley** [wearebraid/vue-formulate#275] opened 2020-10-05 01:01 UTC
**Describe the bug**
When setting up a group in a form schema, there are multiple vue warnings for duplicate keys

`[Vue warn]: Duplicate keys detected: 'el-1-undefined'. This may cause an update error.`

### CodeSandbox

https://codesandbox.io/s/vue-formulate-reproduction-template-forked-8vmhr

**Expected behavior**
No warnings

**Comment by justin-schroeder** [comment] 2020-10-05 01:11
Great! Thanks for the reproduction. It looks like the issue is with the multiple divs at the root. I suspect it would be an issue anytime you have multiple non-input nodes on at a given depth. In a way this was introduced in 2.4.4 since before that keys were not properly being applied, and now in 2.4.4 they are being applied (thus the error), but there's no difference between two divs at a root level 🤔

I swear, generating unique deterministic ids is nearly impossible...until i come up with a fix for this, if you give those divs an `id` it should fix it:

![image](https://user-images.githubusercontent.com/1950463/95031860-29b45300-0686-11eb-93b3-223d936de464.png)

**Comment by lsbyerley** [comment] 2020-10-05 01:23
Ahh yeah you are right, adding an id field to a component div object does seem to resolve the warnings. For some reason I wasn't aware of being able to do that in the schema. Just putting a note in the docs should suffice I would think

**Comment by justin-schroeder** [comment] 2020-11-30 21:06
This is now fixed in `release/2.5` 👍

**Closed as completed by justin-schroeder** 2020-11-30 21:06 UTC
Labels: bug
