### ISSUE TITLE
Question: How to add suffix to the displayed input value only.

### ISSUE THREAD

**Issue by katerlouis** [wearebraid/vue-formulate#337] opened 2020-12-13 22:03 UTC
![image](https://user-images.githubusercontent.com/1983382/102025214-d140b680-3d96-11eb-8b61-bbe7d3fe9181.png)

Similar to how `date` and `time` types already format the `value`, I'd like to append a suffix to the value and display it aswell. In this case the `kg`-unit.

I've briefly looked into custom types and the element slot, but felt overwhelmed and think (or hope?) that this is overkill. Am I missing something here? It feels like this is already possible without much effort.

Just to be clear, the expected value should still be a number (or numeric string, not sure yet– the docs comment about accessibility got me thinking) without the `kg`. But the user should see the kg all the time and not be able to edit it or place the caret there.

How would you suggest doing this with Formulate?

**Comment by justin-schroeder** [comment] 2020-12-14 14:33
Incredibly, this is not as simple as it would appear with HTML forms. My gut reaction would be to use a masking utility (which vue formulate plans to implement in 3.0), something like [vue-the-mask](https://vuejs-tips.github.io/vue-the-mask/), but the reality is that would make the `Kg` part of the input value, in your case you want it to just be a decorative suffix. So ultimately this will come down to styling. There's a[ prefix/suffix issue ](https://github.com/wearebraid/vue-formulate/issues/98)that is being worked on in 2.5 which should give you enough power to make your input do what you want at a dom level. Also on that thread @hmaesta has a great example of doing something similar with tailwind, but ultimately you're looking at some custom css to make this work. Perhaps in Vue Formulate 3.0 we could introduce a `unit` prop and add some of that mojo into the package itself.

For now I'm going to close this as a duplicate of #98, but open to further suggestions along this line of thinking. Good luck 👍

**Closed as completed by justin-schroeder** 2020-12-14 14:33 UTC
Labels: feature request

**Comment by hmaesta** [comment] 2020-12-14 15:39
Just so you don't get stuck and have some inspiration...

Here we created a `percentage` type input that is just a `text` type with a `%` suffix (you can edit and replace to `Kg`).

![ScreenFlow](https://user-images.githubusercontent.com/741969/102101343-4220b680-3e09-11eb-8002-34ef902e098c.gif)


→ https://codesandbox.io/s/vue-formulate-input-percentage-suffix-bmgov

The code is a little messy because I had to remove all the peculiarities we need that probably don't make sense for anyone else. Sorry about that – but I think it's enough so you can bootstrap. 

---

Credits: mostly of this code is by my co-worker @ileonardo-c. _Sorry for messing up your code, Leonardo!_

**Comment by katerlouis** [comment] 2020-12-15 13:12
> Also on that thread @hmaesta has a great example of doing something similar with tailwind, but ultimately you're looking at some custom css to make this work. 

Looked into that, but if I remember correctly this was solved with absolutely positioned elements at the inputs outer edges. I'd really like an inconspicuous suffix. Looked into masking aswell but hoped this could be circumvented. I'm afraid mixing VueFormulate with something else will result in new issues.

**Comment by katerlouis** [comment] 2020-12-15 13:13
> Here we created a `percentage` type input that is just a `text` type with a `%` suffix (you can edit and replace to `Kg`).
@hmaesta thanks a lot! Why the delay on adding the `%`?

**Comment by hmaesta** [comment] 2020-12-15 13:16
When user is typing we don't want to show the `%`, just on blur.

If you need the "Kg" suffix always present, maybe you should use a mask. Take a look here: https://github.com/wearebraid/vue-formulate/issues/67

**Comment by katerlouis** [comment] 2020-12-15 13:19
But I thought a mask also adds the `kg` to the actual value?

**Comment by hmaesta** [comment] 2020-12-15 13:21
I am not sure because I am not a user, but I believe imask (used on previous linked issue) has the option to get the value without the mask.
