### ISSUE TITLE
Slow perfomance to type in input fieds.

### ISSUE THREAD

**Issue by alfredobp** [wearebraid/vue-formulate#566] opened 2022-10-17 10:13 UTC
I am experiencing poor performance when writing to text type input, I think it is due to validation. Is there a way to set the validation to be on the submit event? I have tried both firefox and chrome and the error is similar. It is very inconvenient for the user to fill in the form because they are delayed. Thank you.

![image](https://user-images.githubusercontent.com/55509379/196151753-f0836a00-98f4-4134-81b8-b5e7d8a93cdd.png)

` [

 	{

 		"type": "clientsList",
"name": "clientsList",
"validation-messages":{
"required":"Este campo es obligatorio"
}

 		
},

 	{

 		"type": "hostingPlans",
"name": "hostingPlans",
"validation-messages":{
"required":"Este campo es obligatorio"
}

 		
},

	{
 		"label": "Nombre de la instalación",
 		"name": "name",	"validation": "required|min:3|max:50",
"validation-messages":{"required":"Este campo es obligatorio",
"min":"Intente un nombre de la instalación más largo",
"max":"Intente un nombre de la instalación más corto"
}
 	
 	},
  {
    "label": "Nombre de usuario",
    "name": "user",
    "validation": "required",
"validation-messages":{"required":"Este campo es obligatorio"
}
  },
  {

    "name": "email",
"type":"emailForm",
    "validation": "bail|required|email",
"validation-messages":{"required":"Inserte una dirección de correo electrónico correcta",
"email":"Inserte una dirección de correo electrónico correcta"

}
  },

  {
"type":"passwordGenerate",
   
    "name": "pass",
    "help": "Guarde esta contraseña en un lugar seguro, prodrás cambiarla más adelante"
 },
  {
    "type": "submit",
 "label": "Crear App"
  }]`

**Comment by justin-schroeder** [comment] 2022-10-17 13:51
This is not directly related to validation, and likely a duplicate of #223, I'd recommend jumping over there to learn more about how to add some debouncing or other hacks. However, your best long term bet is to upgrade to FormKit.

**Closed as completed by justin-schroeder** 2022-10-17 13:51 UTC
Labels: duplicate, bug report
