### ISSUE TITLE
Support for `@validation` (and others) in schema for inputs

### ISSUE THREAD

**Issue by engram-design** [wearebraid/vue-formulate#152] opened 2020-07-05 02:22 UTC
**Describe the bug**
There's possibly a few other attributes and cases for this, but It doesn't seem possible to use `@validation` or `@error-behaviour` when using a schema. For example:

```
[
  {
    'label': 'Your name',
    'name': 'name',
    'validation': 'required',
    '@validation': 'validateInput',
  },
]
```

Produces the following error:
```
[Vue warn]: Error in nextTick: "InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '@validation' is not a valid attribute name."
```

I take it this sort of thing just isn't supported at the moment? Ideally, I want to be able to listen to a schema-created field's validation status. I'm aware you can use `@validation` on the form, and am currently using that.

As an aside, it'd be super-neat to be able to provide props and other Vue-related attributes, as per [Vue's render functions](https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth). I've seen this implemented in [vue-form-json-schema](https://github.com/jarvelov/vue-form-json-schema#usage)

**Comment by justin-schroeder** [comment] 2020-07-05 03:42
You can currently pass props, all key/value pairs you define in the schema will be passed as props to any component you define. Events however are still not fully supported. Working on it! 🙂

Technically this is a duplicate of #132 so Let’s carry on the conversation over there!

**Closed as completed by justin-schroeder** 2020-07-05 03:42 UTC
Labels: bug report

**Comment by engram-design** [comment] 2020-07-05 03:45
@justin-schroeder I swear I searched for issues, thanks for pointing me in the right direction though! 😅
